package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/swagger"
	"log"
	_ "testapi/docs" // Import docs generated by swag
	"testapi/internal/constants"
	"testapi/internal/database"
	"testapi/internal/routes"
)

// @title			Test API
// @version		1.0
// @description	This is a sample API for authentication
// @host			localhost:80
// @BasePath		/
// @schemes		http
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	database.InitDB()

	app := fiber.New()

	if constants.IS_DEBUG {
		app.Use(cors.New(cors.Config{
			AllowOrigins: "http://localhost,http://127.0.0.1",
			AllowMethods: "GET,POST,PUT,DELETE,OPTIONS",
			AllowHeaders: "Origin, Content-Type, Accept, Authorization",
		}))

		app.Get("/swagger/*", swagger.HandlerDefault) // http://localhost/swagger/index.html

		app.Get("/", func(c *fiber.Ctx) error {
			//redirect to swagger
			return c.Redirect("/swagger/index.html")
		})
	}

	routes.SetupAuthRoutes(app)

	log.Println("🚀 Server running on http://localhost:80")
	err := app.Listen(":80")

	if err != nil {
		log.Fatal(err)
	}
}
